### ISSUE TITLE
Add compatibility with PHPUnit 7.2

### ISSUE THREAD

**Issue by haeber** [TiMESPLiNTER/proxy-mock#5]
Hi there,

proxy-mock or it's dependencies are not compatible with PHPUnit 7.2. You can reproduce it if you change your require-dev in the composer.json from
`"phpunit/phpunit": "^6.5|^7.0"`
to
`"phpunit/phpunit": "^7.2"`

Goal would be to make it compatible with PHPUnit ^7.2.

Kind Regards
Thomas

**Comment by TiMESPLiNTER** [comment]
Fixed by #6
